version: 2

sources:
  - name: adventureworks
    tables:
      - name: person_address
      - name: person_person 
      - name: production_product
      - name: sales_creditcard
      - name: sales_customer
      - name: sales_salesorderdetail
      - name: sales_salesorderheader
      - name: sales_salesorderheadersalesreason
      - name: sales_salesreason
      - name: sales_salesterritory