
version: 2

models:
    - name: fact_orders
      description: "tabela de fatos"
      columns:
          - name: salesorderid
            description: "a chave primária original da tabela"
            tests:
                - not_null

    - name: dim_customers
      description: "dimensão consumidores"
      columns:
          - name: customerid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_products
      description: "dimensão produtos"
      columns:
          - name: productid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_card
      description: "dimensão Transportadores"
      columns:
          - name: creditcardid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_data
      description: "dimensão fornecedores"
      columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_local
      description: "dimensão fornecedores"
      columns:
          - name: addressid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_reason
      description: "dimensão fornecedores"
      columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - not_null                