
version: 2

models:
    - name: fact_orders
      description: "tabela de fatos pedidos"
      columns:
          - name: salesorderid
            description: "a chave primária original da tabela"
            tests:
                - not_null
                - unique
    - name: fact_order_details
      description: "tabela de fatos pedido item"
      columns:
          - name: salesorderdetailid
            description: "a chave primária original da tabela"
            tests:
                - not_null
                - unique                
    - name: dim_customers
      description: "dimensão consumidores"
      columns:
          - name: customerid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_products
      description: "dimensão produtos"
      columns:
          - name: productid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_card
      description: "dimensão cartão"
      columns:
          - name: creditcardid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_data
      description: "dimensão data"
      columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_local
      description: "dimensão localização"
      columns:
          - name: addressid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_reason
      description: "dimensão motivos"
      columns:
          - name: salesreasonid
            description: "The primary key for this table"
            tests:
                - not_null 
    - name: bridge_reason_order
      description: "Ponte entre motivos e pedidos"
      columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - not_null                